### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by yeedle** [atmist/snazzy-info-window#16]
Using this as an ES6 module (with vue.js + webpack), I cannot import the module , because at the time of import, the `google` global var is not yet created. Instead, I get a `ReferenceError`. Is there a way around this?

**Comment by joelkravets** [comment]
I noticed this problem as well when we were using this project internally in our own ReactJS application.

Instead of using:
`import SnazzyInfoWindow from 'snazzy-info-window';`

Use the following:
`let SnazzyInfoWindow = require('snazzy-info-window');`

The reason the bug exists is because of this line right here:
`export default class SnazzyInfoWindow extends google.maps.OverlayView {`

We might be able to resolve this issue by adding a wrapper object around SnazzyInfoWindow which checks for the existence of google before trying to create the subclass.

Thanks for the feedback. Hopefully the above solution will work for you in the mean time.

**Comment by Yeedle** [comment]
Thanks, the above solution works like a charm. And thanks for responding so fast!

One more question, how do I pull in the css?

**Comment by Yeedle** [comment]
Thanks once again! You're awesome!

**Comment by nicholasgcoles** [comment]
Hi is there a work around for this which does not involve 'require'? I am still getting google not defined issue.

I am using an angular project (without the agm/core component) and so I "declare const google: any" whenever I want to use it.

**Comment by Goldfinch** [comment]
Any updates on this?

I'm using the following as well:
`let SnazzyInfoWindow = require('snazzy-info-window');`

but `Uncaught ReferenceError: google is not defined` still appears occasionally and stops all other scripts

**Comment by pttsky** [comment]
@Goldfinch where exactly do you place that line in the code?

I was having literally the same issue after just replacing `import` to `require` statements in the top of my file. But that changes nothing in general. 

But there is one benefit - you are allowed to use `require` statements anywhere in your file. 

I used `<script src=https://maps.googleapis.com/maps/api/js?key=${apiKey}&callback=initMap async defer'></script>` and then in my JS: 

```
window.initMap = function() {
  const SnazzyInfoWindow = require('snazzy-info-window');
  const popup = document.getElementById(popupId);
  if (!popup) {
      throw new Error(`Cannot find element with id="${popup}"`);
  }
  new SnazzyInfoWindow({ marker, content: popup.innerHTML, ...infoWindowConfig });
}
```

And for these case, `const` is more suitable over `let`.

**Comment by goldfinch** [comment]
@pttsky sorry for the late response,

I solved this issue using callback, to make sure that the google library loads first, eg:

```javascript
<script>
window.initSnazzy = function(){
    
    let SnazzyInfoWindow = require('snazzy-info-window');
    
    // ....
};
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places&callback=initSnazzy"></script>
```
