### ISSUE TITLE
Overflow issues when using Bootstrap dropdowns

### ISSUE THREAD

**Issue by adamkrogh** [atmist/snazzy-info-window#9]
We've noticed an issue when using Bootstrap dropdowns within Snazzy Info Window. When expanded, the content gets scrolled instead of being displayed outside of the info window.

I've created a CodePen illustrating the issue [here](http://codepen.io/snazzymaps/pen/evVWgz).

This is a little difficult to solve since we also want to maintain scrollable content within the info window. The DOM element `si-content` has `overflow: auto` to support scrollable content but this causes scroll bars when the dropdown opens and exceeds the size of the content area.

This is normal behaviour but we just want to open this issue up to see if there is a viable workaround to support plugins like Bootstrap dropdown overflowing outside of the content while still supporting scrollable content.

**Comment by DarcyChan** [comment]
Unfortunately, this issue seems to be a result of the way overflow containers inherently work.

One workaround while still maintaining scrollable content could be to override some of the CSS to allow the overflowing element to be visible and add some JavaScript to the Info Window's open callback to position the element.

CSS:
```
/* Reset the z-index so the dropdown will appear over the info window arrow. */
.si-wrapper-top > * {
	z-index: initial;
}

/* Allow the element to appear outside the wrapper. */
.si-content-wrapper {
	overflow: visible;
}
```

JS:
```
...
callbacks: {
	open: function() {
		$('.dropdown-toggle').dropdown();			
		
		$('.dropdown-container').on('show.bs.dropdown', function () {
			var el = $(this);
			
			// Position the dropdown menu relative to the .si-content-wrapper element.
			$('.dropdown-menu').css({
				'top': el.position().top + el.height(),
				'left': el.position().left
			});
		});
	}
	...
}
...
```
[CodePen example 1](http://codepen.io/snazzymaps/pen/LWdZMv)

This example assumes that the offset parent of the dropdown menu is `.si-content-wrapper`. The dropdown menu is manually positioned because the dropdown container '.dropdown-container' does not have `position:relative` set like it normally would to correctly position it below the toggle. If the closest offset parent to the dropdown menu is `.si-content-wrapper`, then the dropdown will be unaffected by the `overflow:auto` property on the `.si-content` element and overflow outside the window. From there, the dropdown menu can be positioned manually.

Alternatively, if the closest offset parent is not `.si-content-wrapper`, then the dropdown menu could be appended to the `.si-content-wrapper` element to have it appear outside the scroll area. Getting the position would have to be adjusted as well since `.position()` will not be using the offset parent that is needed. The dropdown menu would also need to be manually shown and hidden as Bootstrap normally does it with the `.open` class and CSS on the dropdown container. An example could look something like this (the CSS would be the same as above):

JS:
```
...
callbacks: {
	open: function() {
		$('.dropdown-toggle').dropdown();		
		
		// Move the dropdown menu markup
		$('.dropdown-menu').appendTo('.si-content-wrapper');	
		
		$('.dropdown-container').on('show.bs.dropdown', function () {	
			var toggle = $('.dropdown-toggle');
                        var content = $('.si-content');
			
			// Position the dropdown menu relative to the .si-content-wrapper element.
			$('.dropdown-menu').css({
				'top': toggle.offset().top - content.offset().top + content.position().top + toggle.outerHeight(),
				'left': toggle.offset().left - content.offset().left  + content.position().left
			});
			
			// Show the dropdown
			$('.dropdown-menu').show();
		});
		
		$('.dropdown-container').on('hide.bs.dropdown', function () {	
			// Hide the dropdown menu
			$('.dropdown-menu').hide();
		});
	}
	...
}
...
```
[CodePen example 2](http://codepen.io/snazzymaps/pen/OpvRWm)

Both of these examples behave the same, but depend on the complexity of the markup inside the Info Window.

One issue to this workaround would be that while the dropdown menu is open, it would not scroll with the rest of the content in the Info Window without more JavaScript.

**Comment by DarcyChan** [comment]
We'll close this issue for now and revisit it if becomes a larger issue or another solution appears.
